---
- name: Install Omnibus GitLab prerequisites
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - openssh-server
    - ca-certificates
    - postfix
    - apt-transport-https

- name: Install GitLab apt key
  apt_key:
    url: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
    state: present

- name: Add GitLab apt repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: gitlab_gitlab-ce
  with_items:
    - deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ {{ ansible_distribution_release }} main
    - deb-src https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ {{ ansible_distribution_release }} main

- name: Install GitLab CE
  apt:
    name: gitlab-ce
    state: present
  notify: reconfigure gitlab

- name: Write gitlab.rb file
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    mode: 0600
  notify: reconfigure gitlab
